name: CI

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306

    env:
      DB_HOST: localhost
      DB_NAME: testdb
      DB_USERNAME: testuser
      DB_PASSWORD: testpassword

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Print environment variables
        run: |
          echo "DB_HOST=${DB_HOST}"
          echo "DB_NAME=${DB_NAME}"
          echo "DB_USERNAME=${DB_USERNAME}"
          echo "DB_PASSWORD=${DB_PASSWORD}"

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
        shell: bash
